server:
  port: 8022


spring:
    thymeleaf:
        prefix: classpath:/templates/

    profiles:
        #多个 用逗号(,)隔离 : dev, default
        active: dev

# uid 主键生成配置
uid:
  generator:
#    当前时间，相对于时间基点 epochStr 的增量值，单位：秒，最多可支持约34年
    timeBits: 30
#    机器id，最多可支持约105w次机器启动。内置实现为在启动时由数据库分配，默认分配策略为用后即弃，后续可提供复用策略。
    workerBits: 20
#    每秒下的并发序列，13 bits可支持每秒8192个并发。
    seqBits: 13
#    时间基点
    epochStr: 2020-01-01


#mybatis:
#  mapper-locations: classpath:mapping/**/*.xml
#  type-aliases-package: com.example.demo.model

#pagehelper
pagehelper:
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
#    支持 多种 数据源(Oracle,Mysql,MariaDB,SQLite,Hsqldb,PostgreSQL)
    auto-runtime-dialect: true

# 此处不写的话  spring会自动扫描 log4j2.* 配置文件
logging:
  config: classpath:log4j2.xml



