server:
  port: 8022


spring:
    thymeleaf:
        prefix: classpath:/templates/

    profiles:
        #多个 用逗号(,)隔离 : dev, default, individual
        active: dev

    #配置文件上传大小,这里必须配置,因为默认为1MB,超过上传大小会抛一个异常,可以进行全局异常处理
    servlet:
        multipart:
          max-file-size: 50MB
          max-request-size: 50MB

# uid 主键生成配置
uid:
  generator:
#    当前时间，相对于时间基点 epochStr 的增量值，单位：秒，最多可支持约34年
    timeBits: 30
#    机器id，最多可支持约105w次机器启动。内置实现为在启动时由数据库分配，默认分配策略为用后即弃，后续可提供复用策略。
    workerBits: 20
#    每秒下的并发序列，13 bits可支持每秒8192个并发。
    seqBits: 13
#    时间基点
    epochStr: 2020-01-01


#mybatis:
#  mapper-locations: classpath:mapping/**/*.xml
#  type-aliases-package: com.example.demo.model

mybatis-plus:
  configuration:
    #开启sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性
    map-underscore-to-camel-case: true


#pagehelper
pagehelper:
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
#    支持 多种 数据源(Oracle,Mysql,MariaDB,SQLite,Hsqldb,PostgreSQL)
    auto-runtime-dialect: true

# 此处不写的话  spring会自动扫描 log4j2.* 配置文件
logging:
  config: classpath:log4j2.xml



