ftp:
  default-charset: UTF-8
#  毫秒(millisecond) (second * 1000)
  default-timeout: 60000
  ftpBasePath: /
  hostname: 192.168.1.107
  port: 21
#  username: root
  username: kaifatest
  password: 777777

schedule:
    synchronization:
        test1: 0/3 * * * * ?
        test2: 0/5 * * * * ?
        test3: 0/8 * * * * ?
